spring:
  h2:
    console:
      enabled: true
      path: /test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa